# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2023 Huawei Device Co., Ltd.
#
# Makefile for the Linux PAC module.
#

obj-$(CONFIG_ARM64_PTR_AUTH_EXT) += src/pointer_auth_key.o
obj-$(CONFIG_ARM64_PTR_AUTH_EXT) += src/asm_pointer_auth_key.o
obj-$(CONFIG_ARM64_PTR_AUTH_DATA_FIELD) += src/pointer_auth_context.o
obj-$(CONFIG_ARM64_PTR_AUTH_DATA_FIELD) += src/asm_pointer_auth_context.o
obj-$(CONFIG_CONSTRUCTORS) += src/asm_pointer_auth_constructors.o
